config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :templates, only: %i[new create index]
  resources :to_do_lists do
    patch :move, on: :member
    post :create_from_template, on: :collection
    resources :sections do
      resources :tasks
    end
  end
  root to: "dashboard#index"

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/dashboard_broadcastable.rb
module DashboardBroadcastable
  extend ActiveSupport::Concern

  included do
    after_create_commit { broadcast_to_dashboard }
    after_destroy_commit { broadcast_to_dashboard }
    after_update_commit { broadcast_to_dashboard }
  end

  def broadcast_to_dashboard
    User.find_each { |user| broadcast_for_replace_dashboard(user) }
    broadcast_for_replace_dashboard(nil)
  end

  def broadcast_for_replace_dashboard(user)
    broadcast_replace_to(user ? "dashboard_#{user.id}" : "dashboard", target: "to_do_lists", partial: "dashboard/to_do_lists",
                                                                      locals: {
                                                                        my_to_do_lists: user ? user.to_do_lists.to_a : [],
                                                                        to_do_lists: user ? ToDoList.where.not(user:).to_a : ToDoList.all.to_a,
                                                                        user:
                                                                      })
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/section.rb
class Section < ApplicationRecord
  include DashboardBroadcastable
  validates :title, presence: true

  belongs_to :to_do_list
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  include DashboardBroadcastable

  belongs_to :section
  validates :title, presence: true
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
  include DashboardBroadcastable

  acts_as_list

  validates :title, presence: true

  has_many :sections, dependent: :destroy
  belongs_to :user, default: -> { Current.user }

  default_scope { where(is_template: false) }
  scope :templates, -> { unscoped.where(is_template: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :to_do_lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  default_form_builder TailwindFormBuilder

  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :pundishing_user

  before_action :set_current_user, if: :user_signed_in?

  private

  def pundishing_user
    flash[:notice] = "You are not authorized to perform this action."
    redirect_to root_path
  end

  def set_current_user
    Current.user = current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @my_to_do_lists = ToDoList.where(user: Current.user) if Current.user
    @to_do_lists = ToDoList.where.not(user: Current.user)
    render
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_to_do_list
  before_action :set_section, only: %i[edit update destroy]
  before_action :authorize_user

  def new
    @section = Section.new
  end

  def create
    @section = @to_do_list.sections.new(section_params)
    if @section.save
      render
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @section.update(section_params)
      render
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @section.destroy
  end

  private

  def section_params
    params.require(:section).permit(:title)
  end

  def set_to_do_list
    @to_do_list = ToDoList.find_by(id: params[:to_do_list_id])
  end

  def set_section
    @section = Section.find_by(id: params[:id])
  end

  def authorize_user
    authorize @to_do_list, :update?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_section
  before_action :set_task, only: %i[edit update destroy]
  before_action :authorize_user

  def new
    @task = Task.new
  end

  def create
    @task = @section.tasks.new(task_params)
    if @task.save
      render
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      render
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :description)
  end

  def set_section
    @section = Section.find_by(id: params[:section_id])
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end

  def authorize_user
    authorize @section.to_do_list, :update?
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_to_do_list, only: %i[new create]

  def index
    @templates = ToDoList.templates.where(user: Current.user)
  end

  def new
    @template = ToDoList.new(is_template: true)
  end

  def create
    @template = TemplateCreator.call(@to_do_list, params.dig(:to_do_list, :title))
    if @template.save
      flash[:notice] = "Template successfully created."
    else
      flash[:error] = "Something went wrong."
    end
  end

  private

  def set_to_do_list
    @to_do_list = ToDoList.find_by(id: params[:to_do_list_id])
  end
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_to_do_list, only: %i[edit update destroy move]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    @to_do_list = ToDoList.new
  end

  def create
    @to_do_list = ToDoList.new(to_do_list_params)
    if @to_do_list.save
      render
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create_from_template
    template = ToDoList.templates.find_by(id: params.dig(:to_do_list, :template_id))
    @to_do_list = ToDoListFromTemplateCreator.call(template, Current.user)
    if @to_do_list.save
      render :create
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @to_do_list.update(to_do_list_params)
      render
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @to_do_list.destroy
  end

  def move
    @to_do_list.insert_at(params[:position].to_i)
    head :ok
  end

  private

  def to_do_list_params
    params.require(:to_do_list).permit(:title, :description)
  end

  def set_to_do_list
    @to_do_list = ToDoList.find_by(id: params[:id])
  end

  def authorize_user
    authorize @to_do_list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/dashboard/_to_do_lists.html.erb
<div id="to_do_lists">
  <% if user %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-xl">My To Do lists</h1>
      <div>
        <%= link_to "New To Do list", new_to_do_list_path, class: "px-4 py-2 bg-blue-600 text-white rounded", data: { turbo_frame: "modal" } %>
        <%= link_to "New From Template", new_to_do_list_path(from_template: true), class: "px-4 py-2 bg-blue-600 text-white rounded", data: { turbo_frame: "modal" } %>
      </div>
    </div>
    <div class="flex gap-1 my-5 w-full flex-wrap w-full justify-center" data-controller="drag" data-drag-url="/to_do_lists/:id/move">
      <% my_to_do_lists.sort_by(&:position).each do |to_do_list| %>
        <%= render to_do_list, user: user %>
      <% end %>
    </div>
    <hr>
  <% end %>
  <h1 class="font-bold text-xl my-5">To Do lists from other users</h1>
  <div class="flex gap-5 my-5 w-full flex-wrap justify-center">
    <% to_do_lists.sort_by(&:created_at).each do |to_do_list| %>
      <%= render to_do_list, user: user %>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= turbo_frame_tag "modal" %>
<%= turbo_stream_from Current.user ? "dashboard_#{Current.user.id}" : "dashboard"%>

<%= render "to_do_lists", my_to_do_lists: @my_to_do_lists, to_do_lists: @to_do_lists, user: Current.user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestAppMaindeck</title>
    <meta name="turbo-visit-control" content="reload">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="flex justify-between p-5 bg-blue-200 shadow-md items-center">
      <% if Current.user.present? %>
        <div class="flex gap-5 items-center">
          <div class="font-semibold"> <%= Current.user.email %> </div>
          <%= link_to "Dashboard", root_path, class: "p-2 hover:bg-blue-300 hover:rounded-xl" %>
          <%= link_to "My templates", templates_path, class: "p-2 hover:bg-blue-300 hover:rounded-xl" %>
        </div>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "p-2 hover:bg-blue-300 hover:rounded-xl" %>
      <% else %>
        <div class="font-semibold"> You are not signed in, but still can view lists! </div> 
        <div class="flex gap-5">
          <%= link_to "Sign in", new_user_session_path, class: "p-2 hover:bg-blue-300 hover:rounded-xl" %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "p-2 hover:bg-blue-300 hover:rounded-xl"%>
        </div>
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <main class="mt-28 px-5 w-full text-gray-900">
      <%= yield %>
    </main>
  </body>
</html>

app/views/sections/_form.html.erb
<div class="mb-5">
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: "Title", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none mb-4" %>
  <%= form.error_field :title %>
  <div class="flex justify-end w-full">
    <%= form.submit "Save", class: "px-4 py-2 my-2 bg-blue-600 text-white rounded cursor-pointer" %>
  </div>
</div>

app/views/sections/_section.html.erb
<div class="w-full my-2 px-4 border-b-2" id=<%= dom_id section %>>
  <div class="flex justify-between items-center">
    <h1 class="break-words w-2/3 border-b-2"><%= section.title %></h1>
    <% unless section.to_do_list.is_template || user.blank? %>
      <% if user_policy %>
        <div class="flex gap-1">
          <%= link_to edit_to_do_list_section_path(section.to_do_list, section), class: "flex justify-center gap-1 items-center group text-blue-500", data: { turbo_frame: "modal" } do %>
            <span><%= heroicon "pencil-square", variant: :outline, options: { class: "h-5 w-6" } %></span>
          <% end %>
          <%= link_to to_do_list_section_path(section.to_do_list, section), data: { turbo_method: :delete }, class: "flex justify-center gap-1 items-center group text-red-500" do %>
            <span><%= heroicon "trash", variant: :outline, options: { class: "h-5 w-6" } %></span>
          <% end %>
        </div>
      <% end %>  
    <% end %>
  </div>
  <div class="px-3">
    <div id="section_<%= section.id %>_tasks">
      <% section.tasks.order(created_at: :asc).each do |task|%>
        <%= render task, user: user, user_policy: user_policy %>
      <% end %>
    </div>
  </div>
  <% unless section.to_do_list.is_template || user.blank? || !user_policy %>
    <div class="flex justify-center">
      <div class="w-1/2 p-2 text-sm">
        <div class="p-1 w-full text-gray-500 hover:text-gray-950 hover:border border-blue-300 border-dashed">
          <%= link_to new_to_do_list_section_task_path(section.to_do_list.id, section.id), class: "flex justify-center gap-1 items-center group", data: { turbo_frame: "modal" } do %>
            <span><%= heroicon "plus", variant: :solid, options: { class: "h-5 w-6 " } %></span>
            <span> Add Task</span>
          <% end %>
        </div>
      </div>
    </div>  
  <% end %>
</div>

app/views/sections/create.turbo_stream.erb
<%= turbo_stream.update("modal", "") %>

app/views/sections/destroy.turbo_stream.erb
<%= turbo_stream.remove(@section) %>

app/views/sections/edit.html.erb
<%= render 'shared/modal', title: "Edit Section" do %>
  <%= form_with(model: @section, url: to_do_list_section_path(@to_do_list, @section), class: "mb-7") do |form| %>
    <%= render "form", form: %>
  <% end %>
<% end %>  

app/views/sections/new.html.erb
<%= render 'shared/modal', title: "New Section" do %>
  <%= form_with(model: @section, url: to_do_list_sections_path(@to_do_list), class: "mb-7") do |form| %>
    <%= render "form", form: %>
  <% end %>
<% end %>  

app/views/sections/update.turbo_stream.erb
<%= turbo_stream.update("modal", "") %>

app/views/shared/_modal.html.erb
<% title = local_assigns.fetch(:title, "Modal") %>

<%= turbo_frame_tag "modal" do %>
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4" data-controller="modal" data-modal-target="modal">
    <div class="absolute inset-0 bg-black opacity-50"></div>
    <div class="relative max-w-md mx-auto p-6 bg-white rounded shadow-lg">
      <div class="flex justify-between items-center mb-2">
        <h1 class="font-semibold"><%= title %></h1>
        <%= link_to "", data: { action: "click->modal#close" } do %>
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<div class="mb-5">
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: "Title", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none mb-4" %>
  <%= form.error_field :title %>
  
  <%= form.label :description %>
  <%= form.text_area :description, placeholder: "Description", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
  <%= form.error_field :description %>
  <div class="flex justify-end w-full">
    <%= form.submit "Save", class: "px-4 py-2 my-2 bg-blue-600 text-white rounded cursor-pointer" %>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="w-full my-2" id=<%= dom_id task %>>
  <div class="flex items-center">
    <h1 class="break-words w-2/3"><%= task.title %></h1>
    <% unless task.section.to_do_list.is_template || user.blank? %>
      <% if user_policy %>
        <div class="flex gap-1">
          <%= link_to edit_to_do_list_section_task_path(task.section.to_do_list, task.section, task), class: "flex justify-center gap-1 items-center group text-blue-500", data: { turbo_frame: "modal" } do %>
            <span><%= heroicon "pencil-square", variant: :outline, options: { class: "h-5 w-6" } %></span>
          <% end %>
          <%= link_to to_do_list_section_task_path(task, section_id: task.section.id, to_do_list_id: task.section.to_do_list.id), data: { turbo_method: :delete }, class: "flex justify-center gap-1 items-center group text-red-500" do  %>
            <span><%= heroicon "trash", variant: :outline, options: { class: "h-5 w-6" } %></span>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <h1 class="break-words w-full text-sm text-gray-500"><%= task.description %></h1>
</div>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.update("modal", "") %>

app/views/tasks/destroy.html.erb
<%= turbo_stream.remove(@task) %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove(@task) %>

app/views/tasks/edit.html.erb
<%= render 'shared/modal', title: "Edit Task" do %>
  <%= form_with(model: @task, url: to_do_list_section_task_path(@section.to_do_list, @section, @task), class: "mb-7") do |form| %>
    <%= render "form", form: %>
  <% end %>
<% end %>  

app/views/tasks/new.html.erb
<%= render 'shared/modal', title: "New Task" do %>
  <%= form_with(model: @task, url: to_do_list_section_tasks_path(@section.to_do_list, @section), class: "mb-7") do |form| %>
    <%= render "form", form: %>
  <% end %>
<% end %>  

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.update("modal", "") %>

app/views/templates/index.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold text-xl">Your templates</h1>
</div>
<div class="flex gap-5 my-5 w-full flex-wrap justify-center" id="to_do_lists">
  <% @templates.each do |template|%>
    <%= render template, user: Current.user %>
  <% end %>
</div>

app/views/templates/new.html.erb
<%= render 'shared/modal', title: "New Template" do %>
  <%= form_with(model: @template, url: templates_path(to_do_list_id: @to_do_list), class: "mb-7") do |form| %>
    <%= form.text_field :title, placeholder: "Title", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
    <div class="flex justify-end w-full">
    <%= form.submit "Save", class: "px-4 py-2 my-2 bg-blue-600 text-white rounded cursor-pointer" %>
  </div>
  <% end %>
<% end %>  

app/views/to_do_lists/_form.html.erb
<div class="mb-5">
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: "Title", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none mb-4" %>
  <%= form.error_field :title %>

  <%= form.label :description %>
  <%= form.text_area :description, placeholder: "Description", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
  <%= form.error_field :description %>
  
  <div class="flex justify-end w-full">
    <%= form.submit "Save", class: "px-4 py-2 my-2 bg-blue-600 text-white rounded cursor-pointer" %>
  </div>
</div>

app/views/to_do_lists/_new_from_template.html.erb
<%= form_with(model: @to_do_list, url: create_from_template_to_do_lists_path, class: "mb-7") do |form| %>
  <%= form.label :template_id %>
  <%= form.select :template_id, ToDoList.templates.collect {|t| [ t.title, t.id ] }, {}, class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>  
  <div class="flex justify-end w-full">
    <%= form.submit "Save", class: "px-4 py-2 my-2 bg-blue-600 text-white rounded cursor-pointer" %>
  </div>
<% end %>

app/views/to_do_lists/_to_do_list.html.erb
<div data-id="<%= to_do_list.id %>" class="w-1/3 h-[400px] overflow-y-auto border-2 shadow-md rounded-xl flex flex-col gap-2" id="<%= dom_id to_do_list %>">
  <% user_policy = ToDoListPolicy.new(user, to_do_list).update? %>
  <div class="relative flex justify-between items-center p-2 font-semibold text-lg bg-slate-100">
    <div class="break-words w-2/3"><%= to_do_list.title %></div>
    <% unless to_do_list.is_template || user.blank? %>
      <div class="flex gap-1">
        <%= link_to new_template_path(to_do_list_id: to_do_list.id), data: { turbo_frame: "modal" }, class: "flex justify-center gap-1 items-center group text-blue-500" do %>
          <span><%= heroicon "arrow-down-on-square-stack", variant: :outline, options: { class: "h-5 w-6" } %></span>
        <% end %>
        <% if user_policy %>
          <%= link_to edit_to_do_list_path(to_do_list), class: "flex justify-center gap-1 items-center group text-blue-500", data: { turbo_frame: "modal" } do %>
            <span><%= heroicon "pencil-square", variant: :outline, options: { class: "h-5 w-6" } %></span>
          <% end %>
          <%= link_to to_do_list_path(to_do_list), data: { turbo_method: :delete }, class: "flex justify-center gap-1 items-center group text-red-500" do %>
            <span><%= heroicon "trash", variant: :outline, options: { class: "h-5 w-6" } %></span>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="p-2 font-medium text-sm text-gray-500"><%= to_do_list.description %></div>
  <div id="to_do_list_<%= to_do_list.id %>_sections">
    <% to_do_list.sections.order(created_at: :asc).each do |section|%>
      <%= render section, user_policy: user_policy, user: user %>
    <% end %>
  </div>
  <% unless to_do_list.is_template || user.blank? || !user_policy %>
    <div class="w-full p-2 text-sm">
      <div class="p-1 w-full text-gray-500 hover:text-gray-950 hover:border border-blue-300 border-dashed">
        <%= link_to new_to_do_list_section_path(to_do_list), class: "flex justify-center gap-1 items-center group", data: { turbo_frame: "modal" } do %>
          <span><%= heroicon "plus", variant: :solid, options: { class: "h-5 w-6 " } %></span>
          <span> Add Section</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/to_do_lists/destroy.turbo_stream.erb
<%= turbo_stream.remove(@to_do_list) %>

app/views/to_do_lists/edit.html.erb
<%= render 'shared/modal', title: "Edit To Do list" do %>
  <%= form_with(model: @to_do_list, class: "mb-7") do |form| %>
    <%= render "form", form: %>
  <% end %>
<% end %>  

app/views/to_do_lists/new.html.erb
<%= render 'shared/modal', title: "New To Do list" do %>
  <% if params[:from_template] %>
    <%= render "new_from_template" %>
  <% else %>
    <%= form_with(model: @to_do_list, class: "mb-7") do |form| %>
      <%= render "form", form: %>
    <% end %>
  <% end %>
<% end %>  

app/views/to_do_lists/update.turbo_stream.erb
<%= turbo_stream.update("modal", "") %>